### ISSUE TITLE
do you know about ripgrep?

### ISSUE THREAD

**Issue by Eh2406** [d0ugal/pynd#4]
Hi, I am just a random person on the internet, so don't take what I say to seriously. 

Mostly this is a +1 on your project. I'd love to use tools that can search using python idioms!

Andrew Gallant has been working on an exciting alternative for grp. If you are interested in high performance grp I recommend reading his blog post [ripgrep is faster than {grep, ag, git grep, ucg, pt, sift}](http://blog.burntsushi.net/ripgrep/) or the source code at [ripgrep](https://github.com/BurntSushi/ripgrep). I mostly bring it up as you mention 'grepping huge Python projects' in your blog post.

**Comment by d0ugal** [comment]
Thanks, I think maybe I need to work on my pitch. The goal here isn't speed, but a grep-like tool that works with a Python abstract syntax tree and thus can do much more intelligent searching/filtering.

I hadn't heard of ripgrep, but I'll check it out. I use ack for more general "gripping" like that.

**Comment by Eh2406** [comment]
Cool, I look forward to seeing where your project goes! grep over the ast sounds more flexibil.

ripgrep is much faster than ack, according to his benchmarks.
